name: fretbursts_paper_env

channels:
- tritemio

dependencies:
- appnope=0.1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- freetype=2.5.5=0
- fretbursts=0.5.4=py35_0
- funcsigs=0.4=py35_0
- future=0.15.2=py35_0
- hdf5=1.8.15.1=2
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_0
- jpeg=8d=1
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- llvmlite=0.9.0=py35_0
- lmfit=0.9.2=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.1=0
- mock=1.3.0=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- nose=1.3.7=py35_0
- notebook=4.1.0=py35_2
- numba=0.24.0=np110py35_0
- numexpr=2.5=np110py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2g=0
- pandas=0.18.0=np110py35_0
- path.py=8.1.2=py35_1
- patsy=0.4.0=np110py35_0
- pbr=1.3.0=py35_0
- pexpect=4.0.1=py35_0
- phconvert=0.6.9=py35_0
- pickleshare=0.5=py35_0
- pillow=3.1.1=py35_0
- pip=8.1.1=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.1.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pytables=3.2.2=np110py35_1
- python=3.5.1=0
- python-dateutil=2.5.1=py35_0
- python.app=1.2=py35_4
- pytz=2016.2=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.2.0=py35_0
- readline=6.2=2
- scipy=0.17.0=np110py35_0
- seaborn=0.7.0=py35_0
- setuptools=20.3=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- statsmodels=0.6.1=np110py35_0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - tables==3.2.2
