name: fretbursts_paper_env

channels:
- tritemio

dependencies:
- appnope=0.1.0
- cycler=0.10.0
- decorator=4.0.9
- freetype=2.5.5
- fretbursts=0.5.5
- funcsigs=0.4
- future=0.15.2
- hdf5=1.8.15.1
- ipykernel=4.3.1
- ipython=4.1.2
- ipython_genutils=0.1.0
- ipywidgets=4.1.1
- jbig=2.1
- jinja2=2.8
- jpeg=8d
- jsonschema=2.4.0
- jupyter=1.0.0
- jupyter_client=4.2.2
- jupyter_console=4.1.1
- jupyter_core=4.1.0
- libpng=1.6.17
- libtiff=4.0.6
- llvmlite=0.9.0
- lmfit=0.9.2
- markupsafe=0.23
- matplotlib=1.5.1
- mistune=0.7.2
- mkl=11.3.1
- mock=1.3.0
- nbconvert=4.1.0
- nbformat=4.0.1
- nose=1.3.7
- notebook=4.1.0
- numba=0.24.0
- numexpr=2.5
- numpy=1.10.4
- openssl=1.0.2g
- pandas=0.18.0
- path.py=8.1.2
- patsy=0.4.0
- pbr=1.3.0
- pexpect=4.0.1
- phconvert=0.6.9
- pickleshare=0.5
- pillow=3.1.1
- pip=8.1.1
- ptyprocess=0.5
- pygments=2.1.1
- pyparsing=2.0.3
- pyqt=4.11.4
- pytables=3.2.2
- python=3.5.1
- python-dateutil=2.5.1
- python.app=1.2
- pytz=2016.2
- pyzmq=15.2.0
- qt=4.8.7
- qtconsole=4.2.0
- readline=6.2
- scipy=0.17.0
- seaborn=0.7.0
- setuptools=20.3
- simplegeneric=0.8.1
- sip=4.16.9
- six=1.10.0
- sqlite=3.9.2
- statsmodels=0.6.1
- terminado=0.5
- tk=8.5.18
- tornado=4.3
- traitlets=4.2.1
- wheel=0.29.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - tables==3.2.2
